version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: gobarber
      POSTGRES_PASSWORD: gobarber
      POSTGRES_DB: gobarber
    ports:
      - '5432:5432'
